#!/usr/bin/python
import os

virtenv = os.environ['APPDIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass
#
# IMPORTANT: Put any additional includes below this line.  If placed above this
# line, it's possible required libraries won't be in your searchable path
#

import smtplib

def application(environ, start_response):

        ctype = 'text/plain'
        if environ['PATH_INFO'] == '/submission':
                s=smtplib.SMTP(timeout=10)
                try:
                    s.connect(host="smtp.gmail.com", port=587)
                except Exception, e:
                    response_body = str(e)
                else:
                    response_body = "SUBMISSION SUCCESS"
        elif environ['PATH_INFO'] == '/ssmtp':
                s=smtplib.SMTP_SSL(timeout=10)
                try:
                    s.connect(host="smtp.gmail.com", port=465)
                except Exception, e:
                    response_body = str(e)
                else:
                    response_body = "SSMTP SUCCESS"
        elif environ['PATH_INFO'] == '/smtp':
                s=smtplib.SMTP(timeout=10)
                try:
                    s.connect(host="smtp.gmail.com", port=25)
                except Exception, e:
                    response_body = str(e)
                else:
                    response_body = "SMTP SUCCESS"

        status = '200 OK'
        response_headers = [('Content-Type', ctype), ('Content-Length', str(len(response_body)))]
        start_response(status, response_headers)

        return [response_body]
#
# Below for testing only
#
if __name__ == '__main__':
        from wsgiref.simple_server import make_server
        httpd = make_server('localhost', 8051, application)
        # Wait for a single request, serve it and quit.
        httpd.handle_request()
