#!/usr/bin/python
import os
import commands
from cgi import escape
from urlparse import parse_qs

virtenv = os.environ['APPDIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass
#
# IMPORTANT: Put any additional includes below this line.  If placed above this
# line, it's possible required libraries won't be in your searchable path
# 

def application(environ, start_response):
        params = parse_qs(environ.get('QUERY_STRING', ''))
        ctype = 'text/plain'
        if environ['PATH_INFO'] == '/health':
                response_body = "1"
        elif environ['PATH_INFO'] == '/env':
                response_body = ['%s=%s' % (key, value)
                    for key, value in sorted(os.environ.items())]
                response_body = '\n'.join(response_body)
        else:
                response_body = "Usage: %s/<group>\nValid groups are 'shell', 'mongodb', 'mysql', 'postgresql', 'env'" % (os.environ['OPENSHIFT_APP_DNS'])

        status = '200 OK'
        response_headers = [('Content-Type', ctype), ('Content-Length', str(len(response_body)))]
        #
        start_response(status, response_headers)
        return [response_body]
